#!/bin/bash

#bspc config border_width        6
bspc config border_width        0
bspc config window_gap          $BSPWM_GAP
bspc config focus_follows_pointer true
#bspc config pointer_follows_monitor true
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config auto_cancel true

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config initial_polarity second_child

bspc monitor -d $BSPWM_DESKTOPS

bspc config focused_border_color '#d3d3d3'
bspc config normal_border_color '#4a4a4a'
#bspc config top_padding $PANEL_HEIGHT
#bspc config top_padding 0
#bspc config bottom_padding $PANEL_HEIGHT
#bspc config bottom_padding 0
#bspc config top_padding $(( $BSPWM_GAP ))
#bspc config right_padding $(( $BSPWM_GAP / 2 ))
#bspc config left_padding $(( $BSPWM_GAP / 2 ))
#bspc config top_padding 0
#bspc config bottom_padding $PANEL_HEIGHT
#bspc config bottom_padding $(( $BSPWM_GAP / 2 ))
#bspc config top_padding $(( $BSPWM_GAP / 3 ))
bspc config top_padding 0
bspc config right_padding 0 
bspc config left_padding 0
bspc config bottom_padding $(( $BSPWM_GAP ))

bspc rule -a Gimp floating=on
bspc rule -a mplayer floating=on
bspc rule -a feh floating=on manage=off
bspc rule -a xtut14 floating=on manage=off
bspc rule -a matlab floating=on manage=off

bspc config --subscribe $PANEL_FIFO
