#! /bin/bash

while read -r line ; do
    case $line in
        V*)
            #Volume output
            urxvt -e alsamixer -c0
            ;;
        G*)
            #Space output
            urxvt -e gdmap -f /
            ;;
        D*)
            #Minimize everything
            bspc control --toggle-visibility
            ;;
    esac
done
